### ISSUE TITLE
the result is not safe

### ISSUE THREAD

**Issue by PooiaFerdowsi** [AliChraghi/LanguagesBenchmark#10]
which type of os you are using. if you use of any non self-created os may be other process change the result of speed.
 I hope you understand

**Comment by AliChraghi** [comment]
Pop_OS!

**Comment by PooiaFerdowsi** [comment]
no . I don't say about you distribution . my mean is that when you test sources may be change in your computer processes and program executed slower . so create an operating system and then test. please more read about threads , process ..

**Comment by AliChraghi** [comment]
sadly not possible :)

**Comment by PooiaFerdowsi** [comment]
> sadly not possible :)

sadly not possible ):
