### ISSUE TITLE
Remove "no optimization"

### ISSUE THREAD

**Issue by nsauzede** [AliChraghi/LanguagesBenchmark#6]
I think you should remove every cases of "no optimization"

because :
1. that does not make sense for a (performance) benchmark
2. that only makes the benchmark running longer than needed
2. Rust (mysteriously) dies, giving no results
3. as you mention that doesn't change anything for memleaks
4. Mys doesn't support "no opt", giving no results

**Comment by AliChraghi** [comment]
yes, I agree
